POST {{apiUrl}}/user/login
Content-Type: application/json;charset=UTF-8

{
  "id": "1"
}

> {%
client.global.set("authorizationToken", "Bearer " + response.body.accessToken);
client.log("Auth Token : " + client.global.get("authorizationToken"));
%}

###
POST {{apiUrl}}/user/signup
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name";

테스터1
--boundary
Content-Disposition: form-data; name="nickname";

테스터022
--boundary
Content-Disposition: form-data; name="gender";

MALE
--boundary
Content-Disposition: form-data; name="phoneNum";

010-1234-5678
--boundary
Content-Disposition: form-data; name="job";

대학생
--boundary
Content-Disposition: form-data; name="birth";

1997-01-01
--boundary
Content-Disposition: form-data; name="schoolId";

1
--boundary
Content-Disposition: form-data; name="interestsIds";

1
--boundary
Content-Disposition: form-data; name="interestsIds";

2
###--boundary
###Content-Disposition: form-data; name="avatar"; filename="enjoy.png"

###< ./../main/resources/mock/images/enjoy.png