POST {{apiUrl}}/post/date/5/review
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "postTitle": "게시물 제목",
  "content": "후기작성",
  "time": "60",
  "doDate": "2021-10-02T09:30"
}

###
GET {{apiUrl}}/business/profile/review/1
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/business/profile/1/review/list?page=1&size=5
Authorization: {{authorizationToken}}

###
PUT {{apiUrl}}/business/profile/review/2
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "content": "후기수정2"
}

###
DELETE {{apiUrl}}/business/profile/review/1
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}
