POST {{apiUrl}}/business/profile
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name";

아무개 연구소
--boundary
Content-Disposition: form-data; name="place";

고려대
--boundary
Content-Disposition: form-data; name="contact";

010-1234-1234

###--boundary
#Content-Disposition: form-data; name="avatar"; filename="enjoy.png"
#
#< ./../main/resources/mock/images/enjoy.png

###
GET {{apiUrl}}/business/profile/mine/list
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/business/profile/2
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/business/profile/1
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{authorizationToken}}

--boundary
Content-Disposition: form-data; name="name";

네모 실험실22
--boundary
Content-Disposition: form-data; name="category";

공부
--boundary
Content-Disposition: form-data; name="place";

고려대 신공학관
--boundary
Content-Disposition: form-data; name="introduce";

고려대 실험실 입니다 수정 테스트!
--boundary
Content-Disposition: form-data; name="contact";

010-1234-1111
--boundary
Content-Disposition: form-data; name="avatarChanged";

true


###
DELETE {{apiUrl}}/business/profile/2
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/business/profile/1/share/4
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###
DELETE {{apiUrl}}/business/profile/1/expel/4
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/business/profile/1/expel/2
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/business/profile/3/change/2
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/business/profile/1
Authorization: {{authorizationToken}}


