GET {{apiUrl}}/business/review/list?type=BAD
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/business/1/good-reviews
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/business/1/date/1/review/2
Authorization: {{authorizationToken}}


