POST {{apiUrl}}/business/profile
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name";

동그라미 실험실
--boundary
Content-Disposition: form-data; name="category";

개발
--boundary
Content-Disposition: form-data; name="place";

고려대
--boundary
Content-Disposition: form-data; name="introduce";

고려대 실험실 입니다!
--boundary
Content-Disposition: form-data; name="contact";

010-1234-1234
--boundary
Content-Disposition: form-data; name="avatar"; filename="enjoy.png"

< ./../main/resources/mock/images/enjoy.png

###
GET {{apiUrl}}/business/profile/list/1
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/business/profile/1
Authorization: {{authorizationToken}}

###
PUT {{apiUrl}}/business/profile/3
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "name": "실험실이름수정",
  "category": "실험분야수정",
  "place": "고려대학교수정",
  "contact": "010-1234-5678",
  "introduce": "고려대 실험실 입니다!!!"
}

###
DELETE {{apiUrl}}/business/profile/3
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/business/profile/1/share
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "nickname": "테스터"
}