###
POST {{apiUrl}}/post/2/date/7/apply
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/1/date/1/apply/approve/2
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/1/date/7/apply/reject/3
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/date/1/apply/cancel
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8