POST {{apiUrl}}/post/info
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title";

실험자 모집합니다.
--boundary
Content-Disposition: form-data; name="content";

아무나 오세요~
--boundary
Content-Disposition: form-data; name="place";

고려대 신공학관
--boundary
Content-Disposition: form-data; name="contact";

010-1234-5623
--boundary
Content-Disposition: form-data; name="category";

식품
--boundary
Content-Disposition: form-data; name="headcount";

5
--boundary
Content-Disposition: form-data; name="payment";

CACHE
--boundary
Content-Disposition: form-data; name="cache";

30000
--boundary
Content-Disposition: form-data; name="condition";

true
--boundary
Content-Disposition: form-data; name="conditionDetail";

개발자만|커피좋아하는사람만|ㅎㅎㅎ|
--boundary
Content-Disposition: form-data; name="doTime";

60
--boundary
Content-Disposition: form-data; name="businessProfileId";

1
--boundary
Content-Disposition: form-data; name="schoolId";

1


###
POST {{apiUrl}}/post/7/info/date
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

//{
//  "startDate": "2021-09-01T09:30",
//  "endDate": "2021-09-09T09:30",
//  "doDateList": [
//    "2021-09-03T09:30",
//    "2021-09-03T10:30",
//    "2021-09-03T11:30",
//    "2021-09-03T12:30",
//    "2021-09-04T09:30",
//    "2021-09-05T09:30"
//  ]
//}

{
  "startDate": "2021-09-21T09:30",
  "endDate": "2021-09-24T09:30",
  "doDateList": [
    "2021-09-30T09:30",
    "2021-09-30T10:30",
    "2021-10-01T11:30",
    "2021-10-01T12:30",
    "2021-10-02T09:30",
    "2021-10-02T09:30"
  ]
}

###
DELETE {{apiUrl}}/post/1
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/post/4
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/list/1?doDate=2021-10-01&page=1&size=15&paymentType=&category=&startTime=09:00&endTime=12:35

###
GET {{apiUrl}}/post/1/start?doDate=2021-09-03
###
GET {{apiUrl}}/post/like/list?page=1&size=6
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/apply/approve/list?page=1&size=4
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/apply/list?page=1&size=4&status=APPROVE
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/write/review/list?page=1&size=3
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/business/profile/1/list?page=1&size=5&status=COMPLETE
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/post/4/like
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/post/3/review/13
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "postTitle": "게시물 제목",
  "content": "후기작성",
  "doDate": "2021-09-09T09:30"
}

###
POST {{apiUrl}}/post/3/completed
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}


