POST {{apiUrl}}/post/info
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "title": "커피를 얼마나 마셔야 잠을 못잘까요~",
  "content": "실험 내용",
  "place": "고려대학교 연구실",
  "contact": "010-1234-1234",
  "category": "미디어",
  "headcount": 10,
  "payment": "CACHE",
  "cache": 10000,
  "goods": null,
  "paymentDetail": "계좌로 지급해드립니다.",
  "condition": true,
  "conditionDetail": "커피많이드시는사람|커피좋아하는사람|커피종류많이아는사람",
  "doTime": 60,
  "schoolId": 1,
  "businessProfileId": 1,
  "startDate": "2021-09-20T09:30",
  "endDate": "2021-10-02T12:30",
  "doDateList": [
    {
      "groupId":1,
      "doDate": "2021-09-30T09:30"
    },
    {
      "groupId":2,
      "doDate": "2021-09-30T10:30"
    },
    {
      "groupId":3,
      "doDate": "2021-10-01T11:30"
    },
    {
      "groupId":4,
      "doDate": "2021-10-01T12:30"
    },
    {
      "groupId":1,
      "doDate": "2021-10-02T09:30"
    }
  ]
}


###
POST {{apiUrl}}/post/1/files
Authorization: {{authorizationToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="enjoy.png"

< ./../main/resources/mock/images/enjoy.png

###
DELETE {{apiUrl}}/post/1
Authorization: {{authorizationToken}}

###
GET {{apiUrl}}/post/2
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/list/1?doDate=2021-10-01&page=1&size=15&paymentType=&category=&startTime=09:00&endTime=12:35

###
GET {{apiUrl}}/post/1/start?doDate=2021-09-03
###
GET {{apiUrl}}/post/like/list?page=1&size=6
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/apply/approve/list?page=1&size=4
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/apply/list?page=1&size=4&status=APPROVE
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/write/review/list?page=1&size=3
Authorization: {{authorizationToken}}
###
GET {{apiUrl}}/post/business/profile/1/list?page=1&size=5&status=COMPLETE
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/post/4/like
Authorization: {{authorizationToken}}

###
POST {{apiUrl}}/post/3/review/13
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}

{
  "postTitle": "게시물 제목",
  "content": "후기작성",
  "doDate": "2021-09-09T09:30"
}

###
POST {{apiUrl}}/post/3/completed
Content-Type: application/json;charset=UTF-8
Authorization: {{authorizationToken}}


