POST {{apiUrl}}/post/date/1/apply
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/date/1/finish
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###

POST {{apiUrl}}/post/date/5/apply/approve/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/date/5/apply/approve/cancel/2
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/date/6/apply/reject/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "comment": "조건이 해당하지 않습니다."
}

###
POST {{apiUrl}}/post/date/5/apply/cancel
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

###
POST {{apiUrl}}/post/date/7/attend/change/1
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "isAttend": false
}

###
GET {{apiUrl}}/post/1/applicants?status=APPROVE&doDate=2022-01-07
Authorization: {{authorizationToken}}
