const FeedCategory = [
  { id: 1, icon: "📔", name: "경영/마케팅" },
  { id: 2, icon: "🖥", name: "IT/모바일" },
  { id: 3, icon: "🎨", name: "디자인" },
  { id: 4, icon: "⚽", name: "체육" },
  { id: 5, icon: "🎶", name: "음악" },
  { id: 6, icon: "📖", name: "교육" },
  { id: 7, icon: "🔨", name: "건설" },
  { id: 8, icon: "🎞", name: "미디어/사회" },
  { id: 9, icon: "🏥️", name: "인지/심리" },
  { id: 10, icon: "💉", name: "의료/헬스케어" },
  { id: 11, icon: "🚘", name: "모빌리티" },
  { id: 12, icon: "💰", name: "경제" },
  { id: 13, icon: "🖌", name: "정치" },
  { id: 14, icon: "🍿", name: "생활/문화" },
  { id: 15, icon: "💄", name: "패션/뷰티" },
  { id: 16, icon: "🍽", name: "식품" },
  { id: 17, icon: "🙏", name: "종교" },
  { id: 18, icon: "🏭", name: "제조/공업" },
  { id: 19, icon: "", name: "기타" },
];
export default FeedCategory;
